import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import {NotificationProvider} from "@/context/NotificationContext";
import {SocketProvider} from "@/context/common/SocketContext";
import React from "react";
import ToastProvider from "@/context/ToastContext";
import {ApolloWrapper} from "@/context/ApolloWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <AuthProvider>
        <ApolloWrapper>
        <SocketProvider>
        <NotificationProvider>
          <ToastProvider/>
          <main>{children}</main>
        </NotificationProvider>
        </SocketProvider>
          </ApolloWrapper>
      </AuthProvider>

      </body>
    </html>
  );
}
